//
// ExaHyPE2 solver file
// Generated by Peano's Python API
// www.peano-framework.org
//
// This is generated. If you change fundamental properties, you will have to 
// generate this file. Backup your manual changes before you do so.
//
#ifndef _examples_exahype2_SSInfall_SSInfall_H_
#define _examples_exahype2_SSInfall_SSInfall_H_

#include "AbstractSSInfall.h"
#include "tarch/logging/Log.h"

namespace examples {namespace exahype2 {namespace SSInfall {
  class SSInfall;

}}}


class examples::exahype2::SSInfall::SSInfall: public AbstractSSInfall {
  private:
    static tarch::logging::Log   _log;

  public:
    //int sample_number=10;
    //double m_tot[10]={0,0,0,0,0,0,0,0,0,0};
    //double r_s[10]={0.05*1.732,0.1*1.732,0.15*1.732,0.20*1.732,0.25*1.732,0.3*1.732,0.35*1.732,0.4*1.732,0.45*1.732,0.5*1.732};
    double t_record=0.0;
    const tarch::la::Vector<Dimensions,double> center={0,0,0};
    //double G=1;
    //double t_ini=0.5;
    //double r_ini=0.2;
    //double delta_rho=0.01;
    //double initial_internal_energy=0.1;

    ::exahype2::RefinementCommand refinementCriterion(
      const double * __restrict__ Q, // Q[5+0],
      const tarch::la::Vector<Dimensions,double>&  volumeCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      double                                       t
    ) override;
    


    
    void initialCondition(
      double * __restrict__ Q,
      const tarch::la::Vector<Dimensions,double>&  volumeCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      bool                                         gridIsConstructred
    ) override;
    


    
    void sourceTerm(
      const double * __restrict__ Q,
      const tarch::la::Vector<Dimensions,double>&  volumeCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      double                                       t,
      double                                       dt,
      double * __restrict__ S
    ) override;
    

    
    
    virtual void boundaryConditions(
      const double * __restrict__ Qinside, // Qinside[5+0]
      double * __restrict__ Qoutside, // Qoutside[5+0]
      const tarch::la::Vector<Dimensions,double>&  faceCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      double                                       t,
      int                                          normal
    )  override;
    


    
    double maxEigenvalue(
      const double * __restrict__ Q, // Q[5+0],
      const tarch::la::Vector<Dimensions,double>&  faceCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      double                                       t,
      int                                          normal
    ) override;

      
    


    
    void flux(
      const double * __restrict__ Q, // Q[5+0],
      const tarch::la::Vector<Dimensions,double>&  faceCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      double                                       t,
      int                                          normal,
      double * __restrict__ F // F[5]
    ) override;

    void add_mass(
      const double r_coor,
      const double rho,
      const double size
    );  
    
    double mass_interpolate(
      const double r_coor
    );  

    
};


#endif
