#ifndef _TARCH_MPI_STRINGMESSAGE_H
#define _TARCH_MPI_STRINGMESSAGE_H

#include "mpi.h"
#include "config.h"
#include "peano4/utils/Globals.h"
#ifdef Parallel
	#include "tarch/mpi/Rank.h"
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <complex>
#include <string>
#include <iostream>

namespace tarch {
   namespace mpi {
      class StringMessage;
      class StringMessagePacked;
   }
}

/**
 * @author This class is generated by DaStGen
 * 		   DataStructureGenerator (DaStGen)
 * 		   2007-2009 Wolfgang Eckhardt
 * 		   2012      Tobias Weinzierl
 *
 * 		   build date: 09-02-2014 14:40
 *
 * @date   13/03/2020 13:12
 */
class tarch::mpi::StringMessage { 
   
   public:
      
      typedef tarch::mpi::StringMessagePacked Packed;
      
      struct PersistentRecords {
         /**
          * Generated
          */
         PersistentRecords();
         
         
      };
      private: 
         PersistentRecords _persistentRecords;
         public:

         int _length;
         private:

         public:

         tarch::la::Vector<MPI_MAX_NAME_STRING,short int> _data;
         private:

         
      public:
         /**
          * Generated
          */
         StringMessage();
         
         /**
          * Generated
          */
         StringMessage(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         StringMessage(const int& length, const tarch::la::Vector<MPI_MAX_NAME_STRING,short int>& data);
         
         /**
          * Generated
          */
         virtual ~StringMessage();
         
         /**
          * Generated
          */
          int getLength() const ;
         
         /**
          * Generated
          */
          void setLength(const int& length) ;
         
          tarch::la::Vector<MPI_MAX_NAME_STRING,short int> getData() const ;
         
          void setData(const tarch::la::Vector<MPI_MAX_NAME_STRING,short int>& data) ;
         
          short int getData(int elementIndex) const ;
         
          void setData(int elementIndex, const short int& data) ;
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         StringMessagePacked convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderDestinationRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             * There are two variants: Datatype identifies only those attributes marked with
             * parallelise. FullDatatype instead identifies the whole record with all fields.
             */
            static MPI_Datatype Datatype;
            static MPI_Datatype FullDatatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            enum class ExchangeMode { Blocking, NonblockingWithPollingLoopOverTests, LoopOverProbeWithBlockingReceive };
            
            void send(int destination, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, ExchangeMode mode );
            
            void receive(int source, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, ExchangeMode mode );
            
            static bool isMessageInQueue(int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
            
            int getSenderRank() const;
            #endif
   
};

/**
 * @author This class is generated by DaStGen
 * 		   DataStructureGenerator (DaStGen)
 * 		   2007-2009 Wolfgang Eckhardt
 * 		   2012      Tobias Weinzierl
 *
 * 		   build date: 09-02-2014 14:40
 *
 * @date   13/03/2020 13:12
 */
class tarch::mpi::StringMessagePacked { 
   
   public:
      
      struct PersistentRecords {
         /**
          * Generated
          */
         PersistentRecords();
         
         
      };
      private: 
         PersistentRecords _persistentRecords;
         int _length;
         tarch::la::Vector<MPI_MAX_NAME_STRING,short int> _data;
         
      public:
         /**
          * Generated
          */
         StringMessagePacked();
         
         /**
          * Generated
          */
         StringMessagePacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         StringMessagePacked(const int& length, const tarch::la::Vector<MPI_MAX_NAME_STRING,short int>& data);
         
         /**
          * Generated
          */
         virtual ~StringMessagePacked();
         
         /**
          * Generated
          */
          int getLength() const ;
         
         /**
          * Generated
          */
          void setLength(const int& length) ;
         
          tarch::la::Vector<MPI_MAX_NAME_STRING,short int> getData() const ;
         
          void setData(const tarch::la::Vector<MPI_MAX_NAME_STRING,short int>& data) ;
         
          short int getData(int elementIndex) const ;
         
          void setData(int elementIndex, const short int& data) ;
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         StringMessage convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderDestinationRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             * There are two variants: Datatype identifies only those attributes marked with
             * parallelise. FullDatatype instead identifies the whole record with all fields.
             */
            static MPI_Datatype Datatype;
            static MPI_Datatype FullDatatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            enum class ExchangeMode { Blocking, NonblockingWithPollingLoopOverTests, LoopOverProbeWithBlockingReceive };
            
            void send(int destination, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, ExchangeMode mode );
            
            void receive(int source, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, ExchangeMode mode );
            
            static bool isMessageInQueue(int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
            
            int getSenderRank() const;
            #endif
   
};

#endif

