build1:
  stage: build
  script:
    - cd cookbook && latexmk -shell-escape -view=pdf cookbook.tex


deploy1:
  stage: deploy
  script:
    - scp cookbook/cookbook.pdf "$CIUSER"@"$CIMACHINE":"cookbook_$CI_COMMIT_SHA.pdf"
