#build1:
#  stage: build
#  script:
#    - cd cookbook && latexmk -shell-escape -view=pdf cookbook.tex
#  #  - scp cookbook/cookbook.pdf "$CIUSER"@"$CIMACHINE":"cookbook_$CI_COMMIT_SHA.pdf"
#  artifacts:
#    paths:
#      - cookbook/cookbook.pdf
#    expire_in: 1 week

reframedine:
  stage: build
  tags:
    - done
  script:
    - hostname
    - whoami
    - pwd

hellocosma7:
  stage:
    build
  tags:
    - cosma7
  script:
    - hostname
    - whoami
    - pwd
    - ls
