//
// ExaHyPE2 solver file
// Generated by Peano's Python API
// www.peano-framework.org
//
// This is generated. If you change fundamental properties, you will have to
// generate this file. Backup your manual changes before you do so.
//
#ifndef _{INCLUDE_GUARD}_
#define _{INCLUDE_GUARD}_


{SOLVER_INCLUDES}

#include "toolbox/loadbalancing/RecursiveSubdivision.h"
#include "exahype2/RefinementControl.h"


{OPEN_NAMESPACE}
{SOLVER_DECLARATIONS}
  extern ::exahype2::RefinementControl  refinementControl;

  double getMinTimeStamp();
  double getMaxTimeStamp();
  double getMinTimeStepSize();
  double getMaxTimeStepSize();

  void startTimeStep(
    double globalMinTimeStamp,
    double globalMaxTimeStamp,
    double globalMinTimeStepSize,
    double globalMaxTimeStepSize
  );

  void finishGridConstructionStep();
  void finishTimeStep();
  void finishSimulation();

{CLOSE_NAMESPACE}


#endif
