//
// ExaHyPE2 solver file
// Generated by Peano's Python API
// www.peano-framework.org
//
// This is generated. If you change fundamental properties, you will have to
// generate this file. Backup your manual changes before you do so.
//
#ifndef {% for item in NAMESPACE -%}_{{ item }}{%- endfor %}_{{CLASSNAME}}_H_
#define {% for item in NAMESPACE -%}_{{ item }}{%- endfor %}_{{CLASSNAME}}_H_



#include "toolbox/loadbalancing/RecursiveSubdivision.h"
#include "exahype2/RefinementControl.h"


{% for item in SOLVERS -%}
#include "{{ item[0] }}.h"
{%- endfor %}


{% for item in NAMESPACE -%}
  namespace {{ item }} {
{%- endfor %}

  {% for item in SOLVERS -%}
  extern {{ item[0] }}  {{ item[1] }};
  {%- endfor %}


  extern ::exahype2::RefinementControl  refinementControl;

  {% if LOAD_BALANCER!="" -%}
  extern {{LOAD_BALANCER}}              loadBalancer;
  {% endif -%}


  double getMinTimeStamp();
  double getMaxTimeStamp();
  double getMinTimeStepSize();
  double getMaxTimeStepSize();

  void startGridConstructionStep();
  void startGridInitialisationStep();

  void startTimeStep(
    double globalMinTimeStamp,
    double globalMaxTimeStamp,
    double globalMinTimeStepSize,
    double globalMaxTimeStepSize
  );

  void startPlottingStep(
    double globalMinTimeStamp,
    double globalMaxTimeStamp,
    double globalMinTimeStepSize,
    double globalMaxTimeStepSize
  );

  void finishGridConstructionStep();
  void finishGridInitialisationStep();
  void finishTimeStep();
  void finishPlottingStep();

  void finishSimulation();

{% for item in NAMESPACE -%}
  }
{%- endfor %}


#endif
