//
// ExaHyPE2 solver file
// Generated by Peano's Python API
// www.peano-framework.org
//
// This is generated. If you change fundamental properties, you will have to
// generate this file. Backup your manual changes before you do so.
//
#ifndef _{INCLUDE_GUARD}_
#define _{INCLUDE_GUARD}_


{SOLVER_INCLUDES}


{OPEN_NAMESPACE}
{SOLVER_DECLARATIONS}
{CLOSE_NAMESPACE}


#endif
