//
// Peano4 data file
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff
//
#ifndef _PROJECT_BASE_2D_EULER_INLINE_REPOSITORIES_STEPREPOSITORY_
#define _PROJECT_BASE_2D_EULER_INLINE_REPOSITORIES_STEPREPOSITORY_


#include <string>


namespace project{
namespace base_2d_euler_inline{
namespace repositories{

  class StepRepository;
  /**
   * Forward declarations
   */ 
  class CreateGrid;
  class InitGrid;
  class CreateGridButPostponeRefinement;
  class CreateGridAndConvergeLoadBalancing;
  class PlotSolution;
  class TimeStep;
;
}
}
}



class project::base_2d_euler_inline::repositories::StepRepository {
  public:
    enum class Steps {
      Undef, CreateGrid, InitGrid, CreateGridButPostponeRefinement, CreateGridAndConvergeLoadBalancing, PlotSolution, TimeStep
    };  
    
    /**
     * Convert step into string
     */
    static std::string toString( Steps value ); 
    
    /**
     * Convert step into program step, so you can use it in 
     * peano4::parallel::Node::getInstance().setNextProgramStep()
     */
    static int   toProgramStep( Steps value ); 
    static Steps toStepEnum( int value ); 
};

#endif
  
