//
// ExaHyPE2 solver file
// Generated by Peano's Python API
// www.peano-framework.org
//
// This is generated. If you change fundamental properties, you will have to 
// generate this file. Backup your manual changes before you do so.
//
#ifndef _EXAMPLES_EXAHYPE2_FINITEVOLUMES_LOH1_
#define _EXAMPLES_EXAHYPE2_FINITEVOLUMES_LOH1_


#include "AbstractLOH1.h"

#include "tarch/logging/Log.h"


namespace examples{
namespace exahype2{
namespace finitevolumes{

  class LOH1;
}
}
}



class examples::exahype2::finitevolumes::LOH1: public AbstractLOH1 {
  private:
    static tarch::logging::Log   _log;

  public:
    /**
     * @param Q Vector of unknowns
     * @param x Position of unknowns (finite volume centre)
     * @param h Mesh size of finite volume
     * @param t Time
     */
    ::exahype2::RefinementCommand refinementCriterion(
      double Q[9],
      const tarch::la::Vector<Dimensions,double>&  x,
      const tarch::la::Vector<Dimensions,double>&  h,
      double                                       t
    ) override;

    void adjustSolution(
      double Q[9],
      const tarch::la::Vector<Dimensions,double>&  volumeCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      double                                       t
    ) override;

    void eigenvalues(
      double                                       Q[9],
      const tarch::la::Vector<Dimensions,double>&  faceCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      double                                       t,
      int                                          normal,
      double                                       lambda[9]
    ) override;

    void flux(
      double                                       Q[9],
      const tarch::la::Vector<Dimensions,double>&  faceCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      double                                       t,
      int                                          normal,
      double                                       F[9]
    ) override;

    void boundaryConditions(
      double                                       Qinside[9],
      double                                       Qoutside[9],
      const tarch::la::Vector<Dimensions,double>&  faceCentre,
      const tarch::la::Vector<Dimensions,double>&  volumeH,
      double                                       t,
      int                                          normal
    ) override;
};


#endif
