//
// Peano4 data file
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff
//
#ifndef __PROJECT_BASE_2D_EULER_INLINE_CONSTANTS__
#define __PROJECT_BASE_2D_EULER_INLINE_CONSTANTS__


#include <string>


#include <bitset>



namespace project{
namespace base_2d_euler_inline{

  const std::initializer_list<double> DomainOffset = {0.0,0.0};
  const std::initializer_list<double> DomainSize = {1.0,1.0};
  constexpr auto TerminalTime = 0.1;
  constexpr auto FirstPlotTimeStamp = 0.0;
  constexpr auto TimeInBetweenPlots = 0.001;
  constexpr auto PlotterPrecision = 5;
  const std::bitset<2> PeriodicBC = 0;
  const std::string BuildInformation = "python3  euler2D.py";
  const std::string ConfigureInformation = "$ ./configure --enable-exahype --enable-blockstructured --enable-loadbalancing --bindir=/home/jack/dis/Peano/bindir";

}
}


#endif


