//
// Peano4 data file
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff
//
#ifndef __ENCLAVESPH_CONSTANTS__
#define __ENCLAVESPH_CONSTANTS__


#include <string>





namespace enclavesph{

  const double GAMMA = 1.6666666666666667;
  const double DYNAMIC_VISCOSITY = 0.00001;
  const double CUBIC_SPLINE_SIGMA = 0.4547284088339867;
  const double TARGET_PARTICLE_SIZE = 0.01;
  const double ENERGY_SPIKE = 0.1;
  const double SPIKE_RADIUS = 0.08;
  const double REST_DENSITY = 1;
  const double INITIAL_H = 0.02;
  const auto DOMAIN_OFFSET = {0.0, 0.0};
  const auto DOMAIN_SIZE = {1.0, 1.0};
  const auto EXPLOSION_CENTRE = {0.5, 0.5};

}


#endif


