//
// Peano4 default main header file
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff, i.e. ensure first
// whether file is maybe overwritten by Python generator/API.
//
#ifndef _sphEnclaves_sphEnclaves_MAIN_
#define _sphEnclaves_sphEnclaves_MAIN_


#include <string>


namespace sphEnclaves{

  int main(int argc, char** argv);
}


#endif
