//
// Peano4 data file
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff
//
#ifndef _project_base_2d_euler_inline_celldata_euler2DQ_H_
#define _project_base_2d_euler_inline_celldata_euler2DQ_H_



#include <string>

#include "tarch/la/Vector.h"
#include "tarch/mpi/mpi.h"

#include "peano4/utils/Globals.h"

#include "peano4/datamanagement/CellMarker.h"
#include "peano4/datamanagement/FaceMarker.h"
#include "peano4/datamanagement/VertexMarker.h"


namespace project {namespace base_2d_euler_inline {namespace celldata {

  class euler2DQ;

}}}



struct project::base_2d_euler_inline::celldata::euler2DQ {
  #if PeanoDebug>=1
  private:
    tarch::la::Vector<Dimensions,double> _debugX;
    tarch::la::Vector<Dimensions,double> _debugH;
  
  public:
    void setDebugX( const tarch::la::Vector<Dimensions,double>& data );
    void setDebugH( const tarch::la::Vector<Dimensions,double>& data );
    tarch::la::Vector<Dimensions,double> getDebugX() const;
    tarch::la::Vector<Dimensions,double> getDebugH() const;
  #endif

  #if Dimensions==2
  double                                 value[36];
  #else
  double                                 value[108];
  #endif
  
  euler2DQ();
  euler2DQ(const euler2DQ& other);
  euler2DQ& operator=(const euler2DQ& other);

  std::string toString() const;
  
  void merge(const euler2DQ& neighbour, const peano4::datamanagement::CellMarker& marker);
  static bool send(const peano4::datamanagement::CellMarker& marker);
  static bool receiveAndMerge(const peano4::datamanagement::CellMarker& marker);
  static bool storePersistently(const peano4::datamanagement::CellMarker& marker);
  static bool loadPersistently(const peano4::datamanagement::CellMarker& marker);
  #ifdef Parallel
  /**
   * Sets the Datatype to MPI_Double.
   */
  static void initDatatype();

  /**
   * Degenerates to nop here, but we need such a function to fit to all other types.
   */
  static void shutdownDatatype();
  
  /**
   * Map each entry to an MPI_DOUBLE.
   */
  static MPI_Datatype   Datatype;
  #endif
};


#endif