//
// Peano4 data file
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff
//
#ifndef __EXAMPLES_EXAHYPE2_ACOUSTICS_CONSTANTS__
#define __EXAMPLES_EXAHYPE2_ACOUSTICS_CONSTANTS__


#include <string>



namespace examples{
namespace exahype2{
namespace acoustics{

  constexpr auto DomainOffset = {0.0,0.0};
  constexpr auto DomainSize = {1.0,1.0};
  constexpr auto TerminalTime = 0.005;
  constexpr auto FirstPlotTimeStamp = 0.0;
  constexpr auto TimeInBetweenPlots = 0.001;

}
}
}


#endif


