//
// Peano4 data file
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff
//
#ifndef _EXAMPLES_EXAHYPE2_EULER_OBSERVERS_STEPREPOSITORY_
#define _EXAMPLES_EXAHYPE2_EULER_OBSERVERS_STEPREPOSITORY_


#include <string>


namespace examples{
namespace exahype2{
namespace euler{
namespace observers{

  class StepRepository;
  /**
   * Forward declarations
   */ 
  class CreateGrid;
  class InitGrid;
  class CreateGridButPostponeRefinement;
  class PlotSolution;
  class TimeStep;
;
}
}
}
}



class examples::exahype2::euler::observers::StepRepository {
  public:
    enum class Steps {
      Undef, CreateGrid, InitGrid, CreateGridButPostponeRefinement, PlotSolution, TimeStep
    };  
    
    /**
     * Convert step into string
     */
    static std::string toString( Steps value ); 
    
    /**
     * Convert step into program step, so you can use it in 
     * peano4::parallel::Node::getInstance().setNextProgramStep()
     */
    static int   toProgramStep( Steps value ); 
    static Steps toStepEnum( int value ); 
};

#endif
  
