//
// Peano4 data file
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff
//
#ifndef __EXAMPLES_EXAHYPE2_SWE_CONSTANTS__
#define __EXAMPLES_EXAHYPE2_SWE_CONSTANTS__


#include <string>


#include <bitset>



namespace examples{
namespace exahype2{
namespace swe{

  const std::initializer_list<double> DomainOffset = {0.0,0.0};
  const std::initializer_list<double> DomainSize = {1.0,1.0};
  constexpr auto TerminalTime = 0.001;
  constexpr auto FirstPlotTimeStamp = 0.0;
  constexpr auto TimeInBetweenPlots = 1e-05;
  constexpr auto PlotterPrecision = 5;
  const std::bitset<2> PeriodicBC = 0;

}
}
}


#endif


